name: Build and Push Docker image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set date-based tag
        run: echo "DATE_TAG=$(TZ='Asia/Shanghai' date +'%Y.%m.%-d')" >> $GITHUB_ENV

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/maojiaxing/cloudflared:${{ env.DATE_TAG }}.1
            ghcr.io/maojiaxing/cloudflared:latest
